services:
  backend:
    restart: "no"
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command: bash /app/scripts/start-reload.sh
