[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.1"
sqlalchemy = "^2.0.31"
alembic = "^1.13.2"
passlib = {version = "^1.7.4", extras = ["bcrypt"]}
python-multipart = "^0.0.9"
python-jose = {version = "^3.3.0", extras = ["cryptography"]}
langchain = "^0.2.14"
langchain-community = "^0.2.12"
transformers = "^4.44.1"
pytz = "^2024.1"
langsmith = "^0.1.99"
langchain-chroma = "^0.1.3"
pypdf = "^4.3.1"
sentence-transformers = "^3.0.1"
pydantic-settings = "^2.5.2"
psycopg = {version = "^3.2.2", extras = ["binary", "pool"]}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
